apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/common
  - secret.yaml
patches:
  - path: serviceaccount-patch.yaml
    target:
      kind: ServiceAccount
      name: workload-identity-sa
      namespace: external-dns

