apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds-bootstrap
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system           # <-- your main repo source name
  path: ./infrastructure/controllers/nginx-gateway-fabric/crds