---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: external-dns
type: Opaque
data:
  azure.json: ICAgIHsNCiAgICAidGVuYW50SWQiOiAiNWJkOWNmMmQtMDI0MS00ODQ2LThkMTMtNmNlNTljNjg5Y2M1IiwNCiAgICAic3Vic2NyaXB0aW9uSWQiOiAiMjMyOTg3NmEtZGQxZS00ZDE3LTlkN2UtNjUwNDAyNGRkNTAwIiwNCiAgICAicmVzb3VyY2VHcm91cCI6ICJkbnMtcmctMzAxMjUiLA0KICAgICJ1c2VXb3JrbG9hZElkZW50aXR5RXh0ZW5zaW9uIjogdHJ1ZQ0KICAgIH0=