---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
  labels:
    cert-manager.io/disable-validation: "true"
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 10m
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
  ref:
    semver: "2.0.*"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
    namespace: nginx-gateway
  install:
    crds: Create
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  # values:
  #   nginx:
  #     service:
  #       type: NodePort
  