apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: public
      namespace: nginx-gateway
    patch: |
      - op: add
        path: /spec/listeners/-
        value:
          name: https
          protocol: HTTPS
          port: 443
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: cert-testhop-xyz   
          allowedRoutes:
            namespaces:
              from: All
          hostname: "testhop.xyz"
