---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  interval: 1m
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: OCIRepository
        name: external-dns
        namespace: flux-system
      version: "0.13.12" # Replace with desired chart version
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
      mode: warn
  targetNamespace: external-dns