apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/controller
patches:
  - path: helmrelease-values-patch.yaml
    target:
      kind: HelmRelease
      name: external-dns
      namespace: flux-system
